# Development overrides for docker-compose.yml
version: '3.8'

services:
  api-gateway:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      # Mount source code for development (hot reload)
      - ./src:/app/src:ro
      - ./logs:/app/logs
    command: ["npm", "run", "dev"]
    networks:
      - atma-network
