version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: .
    container_name: atma-api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - ARCHIVE_SERVICE_URL=http://archive-service:3002
      - ASSESSMENT_SERVICE_URL=http://assessment-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3005
      - CHATBOT_SERVICE_URL=http://chatbot-service:3006
      - ADMIN_SERVICE_URL=http://admin-service:3007
      - JWT_SECRET=development_jwt_secret_key
      - INTERNAL_SERVICE_KEY=development_internal_service_key
      - RATE_LIMIT_WINDOW_MS=600000
      - RATE_LIMIT_MAX_REQUESTS=5000
      - ALLOWED_ORIGINS=*
      - LOG_LEVEL=debug
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
      - ./package.json:/app/package.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - atma-network
    depends_on:
      - redis

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: atma-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - atma-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: atma-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api-gateway
    restart: unless-stopped
    networks:
      - atma-network

  # Mock services for development (optional)
  mock-auth-service:
    image: mockserver/mockserver:latest
    container_name: mock-auth-service
    ports:
      - "3001:1080"
    environment:
      - MOCKSERVER_SERVER_PORT=1080
      - MOCKSERVER_LOG_LEVEL=INFO
    volumes:
      - ./mocks/auth-service:/config
    networks:
      - atma-network

  mock-archive-service:
    image: mockserver/mockserver:latest
    container_name: mock-archive-service
    ports:
      - "3002:1080"
    environment:
      - MOCKSERVER_SERVER_PORT=1080
      - MOCKSERVER_LOG_LEVEL=INFO
    volumes:
      - ./mocks/archive-service:/config
    networks:
      - atma-network

  mock-assessment-service:
    image: mockserver/mockserver:latest
    container_name: mock-assessment-service
    ports:
      - "3003:1080"
    environment:
      - MOCKSERVER_SERVER_PORT=1080
      - MOCKSERVER_LOG_LEVEL=INFO
    volumes:
      - ./mocks/assessment-service:/config
    networks:
      - atma-network

  # Monitoring stack
  prometheus:
    image: prom/prometheus:latest
    container_name: atma-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - atma-network

  grafana:
    image: grafana/grafana:latest
    container_name: atma-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    restart: unless-stopped
    networks:
      - atma-network
    depends_on:
      - prometheus

volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  atma-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
