tunnel: 25cefe3f-7c2f-42ce-9f65-ee368353c3d2
credentials-file: C:\Users\rayin\.cloudflared\25cefe3f-7c2f-42ce-9f65-ee368353c3d2.json

# Force HTTP/2 protocol for better stability
protocol: http2

ingress:
  # ATMA Backend API
  - hostname: api.chhrone.web.id
    service: http://localhost:3000
  
  # Jika ada frontend yang berjalan di port lain
  # - hostname: atma-app.yourdomain.com
  #   service: http://localhost:3000
  
  # Catch-all rule (wajib ada di akhir)
  - service: http_status:404
